# Generated by Django 4.2.7 on 2024-02-09 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("GReview", "0002_task_alter_codesubmission_id_alter_feedback_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
