# Generated by Django 4.2.7 on 2024-02-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GReview", "0003_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
